name: build-extension

on:
  push:
    branches:
      - master
    strategy:
      matrix:
        node-version: 14.20.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout action
        uses: actions/checkout@v2

      - name: Build extension
        run: |
          sudo apt-get update
          sudo apt-get install sass -y
          npm i
          npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Copy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          FOLDER: dist
          REPO: self
          BRANCH: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build from {sha}"
